"""Fix dob column type

Revision ID: 94bd393b61f1
Revises: 7063c07efc87
Create Date: 2024-12-16 15:04:14.615896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94bd393b61f1'
down_revision: Union[str, None] = '7063c07efc87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'dob',
               existing_type=sa.VARCHAR(),
               type_=sa.TIMESTAMP(),
               postgresql_using="dob::timestamp without time zone",
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'dob',
               existing_type=sa.TIMESTAMP(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
