"""change sid to uid in staff table

Revision ID: b5dca0fc9cb6
Revises: a077c1826706
Create Date: 2024-11-07 22:32:07.850457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5dca0fc9cb6'
down_revision: Union[str, None] = 'a077c1826706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('uid', sa.UUID(), nullable=False))
    op.drop_column('staff', 'sid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('sid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('staff', 'uid')
    # ### end Alembic commands ###
