"""add (is_admin) column

Revision ID: e8b50bb4a08b
Revises: ba91517c21d2
Create Date: 2024-12-09 14:41:44.169428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8b50bb4a08b'
down_revision: Union[str, None] = 'ba91517c21d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'is_admin')
    # ### end Alembic commands ###
